---
abstract: 'A bundle of various MIDI and music modules'
author:
  - 'Gene Boggs <gene@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bundle-Music
requires:
  File::Format::RIFF: 0
  String::Approx: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Bundle-Music
  repository: https://github.com/ology/Music/tree/master/Bundle-Music
version: 0.0103
